apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
  labels:
    app: springboot
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot-container
        image: 476114111535.dkr.ecr.us-east-1.amazonaws.com/myrepo:latest  
        ports:
        - containerPort: 8080
        env:
        - name: JAVA_HOME
          value: "/usr/lib/jvm/java-21-openjdk-amd64"
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"  
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      restartPolicy: Always
